# Generated by Django 5.0.7 on 2025-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ipp", models.CharField(max_length=30, unique=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "maiden_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "residence_address",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "residence_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "residence_city",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "residence_zip_code",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "residence_latitude",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "residence_longitude",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "coordinates",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("death_code", models.CharField(blank=True, max_length=2, null=True)),
                ("death_date", models.DateTimeField(blank=True, null=True)),
                (
                    "birth_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birth_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "birth_zip_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("birth_latitude", models.FloatField(blank=True, null=True)),
                ("birth_longitude", models.FloatField(blank=True, null=True)),
                ("update_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dwh_patient",
                "indexes": [
                    models.Index(fields=["last_name"], name="dwh_patient_last_na_362906_idx"),
                    models.Index(fields=["first_name"], name="dwh_patient_first_n_9c3e83_idx"),
                    models.Index(fields=["maiden_name"], name="dwh_patient_maiden__39d094_idx"),
                    models.Index(fields=["ipp"], name="dwh_patient_ipp_63110c_idx"),
                ],
            },
        ),
    ]
